%\VignetteIndexEntry{User guide of benchmarkR}
%\VignettePackage{benchmarkR}
%\VignetteEngine{knitr::knitr}
\documentclass[12pt]{article}

<<knitr, echo=FALSE, results="hide", warning=FALSE>>=
library("knitr")
opts_chunk$set(tidy=FALSE,dev="png",fig.show="hide",
               fig.width=4,fig.height=4.5,
               message=FALSE)
@ 

<<style, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

<<load_benchmarkR, echo=FALSE>>=
library("benchmarkR")
@
\usepackage{hyperref}
\usepackage{tocloft}
\usepackage{float}
\usepackage{newfloat}
\usepackage[tableposition=top]{caption}
\usepackage{tikz}
\usetikzlibrary{shapes,arrows}
\usepackage{booktabs}% http://ctan.org/pkg/booktabs
\newcommand{\tabitem}{\,\,\llap{\textbullet}\,\,}

\newcommand{\exitem}[3]{%
  \item \texttt{\textbackslash#1\{#2\}} #3 \csname#1\endcsname{#2}.%
}

\DeclareFloatingEnvironment[name={Example},fileext=lsf,listname={List of Examples}]{example}

\title{User's guide to the ``benchmarkR'' package}
\author{Xiaobei Zhou, Charity Law, Mark D. Robinson}

\begin{document}

\maketitle

\tableofcontents
\listofexamples
\thispagestyle{empty}
\clearpage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Preliminaries}

%\begin{abstract}
% /Bioconductor \cite{Gentleman2004}

\Rpackage{benchmarkR} is an R package designed with a simple purpose: to calculate, evaluate and
visualize the performance of a classification method (e.g., a statistical method that returns p-values), such as those common in statistical genomics.
For example, much of our research has been related to methods to find differentially expressed genes,
differential splicing, differential methylation and so on.  In principle, \Rpackage{benchmarkR} can
be used for any similar situation, for example, where statistical tests are conducted
across the features (e.g., genes) of a dataset and one wants to contrast sensitivity and false
positive (discovery) rates.
The package would typically be used for synthetic datasets or for datasets that are accompanied by independent
validated ``truth'' (in quotes because validation data are typically measured with some uncertainty).

Researchers already look at the performance of methods through simulations using ROC curves,
precision-recall plots, false detection plots and the like -- so, what does \Rpackage{benchmarkR} offer?
In these plots, we are often interested to know at the same time whether methods are
``calibrated'', that is, do the methods actually achieve the false discovery control that the cutoffs 
used would suggest?  The main idea behind the \Rpackage{benchmarkR} package is to simply augment the
the set of standard plots that many methodologists already look at, with some additional calibration information.  
To do this, we in fact make use of the excellent codebase available in the \Rpackage{ROCR} package for
performance assessment.

The typical usage of the \Rpackage{benchmarkR} package would involve p-values, in order to do a calibration assessment.  More generally, the package will happily take ``scores'', but in this case, no calibration assessment can be done.


This guide provides an overview of the \Rpackage{benchmarkR} package and
detailed information on how to use it across the different types of plots and features to customize the visualizations.

\vspace{1em}
\begin{center}
    \begin{tabular}{ | l | }
      \hline
      \textbf{benchmarkR version:} \Sexpr{packageDescription("benchmarkR")$Version} \\
      \hline
\end{tabular}
\end{center}
\vspace{1em}
\begin{center}
    \begin{tabular}{ | l | }
      \hline
      \textbf{Cittation:} \\
      \\
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\\
      \hline
\end{tabular}
\end{center}
\vspace{1em}

% \end{abstract}


\section{Abbreviations}
These abbreviations are used through the whole user guide:
\vspace{1em}
\begin{center}
   \begin{tabular}{ | l | }
      \hline
      \textbf{Abbreviations:} \\
      \\
      \tabitem ROC: receiver operating characteristic \footnotemark \\
      \tabitem TPR: true positive rate\\
      \tabitem FPR: false positive rate\\
      \tabitem FDR: false discovery rate\\  
      \tabitem FD: false discovery \\
      \tabitem BH: Benjamini \& Hochberg \cite{Benjamini1995}\\       
      \hline 
\end{tabular}
\end{center}
\vspace{1em}

\footnotetext{See details from: \url{http://en.wikipedia.org/wiki/Receiver_operating_characteristic}.}


\section{A quick start}
In the simplest case, \Rpackage{benchmarkR} would start with a set of p-values and corresponding truth labels and a call will be made to one of the plotting functions, as follows:\\ 
\begin{example}[H]                 
\centering
<<quick, eval=FALSE>>=
library(benchmarkR)
re <- SimResults(pval,labels)
benchmarkR(re)

rocX(re)
fdX(re)
powerFDR(re)
@
\caption[A quick start]{A quick start} 
\label{quick}
\end{example}

\section{A short summary of \Rpackage{benchmarkR}}
\Rpackage{benchmarkR} is an R package designed to evaluate and visualize classification performance for reference datasets.  Generally speaking, 
the \Rpackage{benchmarkR} package can be divided into two major parts:\\
\begin{enumerate}
  \item \Rclass{SimResults}:  a S4 class object to store the p-values, true labels and other necessary values for further analysis and evaluation.
  \item \Rfunction{benchmarkR}: a method to produce a visualized benchmark result including a 3-panel plot of a ROC curve (\Rfunction{rocX}), a false discovery (FD) plot (\Rfunction{fdX}) and a true-positive-rate versus achieved false-discovery plot(\Rfunction{powerFDR}).
\end{enumerate}
Its whole structure is shown below:\\
  
\begin{center}    
\begin{tikzpicture}[node distance = 2cm, auto]
    % Place nodes
    \node(input) [rectangle, draw] {input data: pval, padj, labels};
    \node(SimResults)[ellipse, draw, below of=input]  {\Rfunction{SimResults}};
    \node(benchmarkR)[ellipse, draw, below of=SimResults]  {\Rfunction{benchmarkR}};
    \node(fdX)[diamond, draw, below of=benchmarkR]  {\Rfunction{fdX}};
    \node(rocX)[diamond, draw, left of=fdX]  {\Rfunction{rocX}};
    \node(powerFDR)[diamond, draw, right of=fdX]  {\Rfunction{powerFDR}};
    \node(other)[diamond, draw, right of=powerFDR]  {\Rfunction{...}};
    % line
    \path [draw, -latex',dashed] (input) -- (SimResults);
    \path [draw, -latex',dashed] (SimResults) -- (benchmarkR);
    \path [draw, -latex',dashed] (benchmarkR) -- (fdX);
    \path [draw, -latex',dashed] (benchmarkR) -- (powerFDR);
    \path [draw, -latex',dashed] (benchmarkR) -- (rocX);
    \path [draw, -latex',dashed] (benchmarkR) -| (other);
\end{tikzpicture}
\end{center}

The individual methods, \Rfunction{rocX}, \Rfunction{fdX}, \Rfunction{powerFDR}, can be called individually and can be highly customized.


\vspace{1em}
\begin{center}
   \begin{tabular}{ | l | }
      \hline
      \textbf{Customized methods:} \\
      \\
      \tabitem  \Rfunction{rocX}: ROC curve augmented with X point\\
      \tabitem  \Rfunction{fdX}: false discovery plot augmented with X point\\    
      \tabitem  \Rfunction {powerFDR}: power (TPR) versus achieved false discovery rate (FDR) plot \\
      \hline 
\end{tabular}
\end{center}
\vspace{1em}

More details of these can be found at Section \ref{sec:powerFDR}, \ref{sec:rocX} and \ref{sec:fdX}.


%---------------------------------------------------------
\section{Data preparation: build a Rclass{SimResults} object}
\label{sec:data}

To use the \Rpackage{benchmarkR} package, it is best to build a \Robject{SimResults} object, which is 
just a container for the results. A \Robject{SimResults} object contains three basic inputs: 
\begin{itemize}
  \item \Robject{pval}: a vector or matrix containing p-values from a classifier or a test.
  \item \Robject{padj}: a vector or matrix containing the adjusted p-values (optional).
  \item \Robject{labels}: a numeric vector indicating class labels (positives with 1, negatives with 0).  For more details, see \Rfunction{?ROCR::prediction}. 
\end{itemize}

The function \Rfunction{SimResults} is just the constructor to build a \Rclass{SimResults} object.  To give a practical example, 
we have pre-packaged the simulation results from Zhou et al. (2014) \cite{Zhou2014a} to
highlight the construction of a \Rclass{SimResults} object (see also \Rfunction{help("Pickrell")}): \\

\begin{example}[H]
\centering
 <<practica,message=TRUE>>=
library(benchmarkR)
data(Pickrell)
re <- SimResults(pval=Pickrell$pval, labels=Pickrell$labels)
re
@
\caption[A practical example -- \Robject{pval} is a matrix]{A practical example -- \Robject{pval} is a matrix}
\label{practical}
\end{example}


In this example,  adjusted p-values (\Robject{padj}) are missing.  In this case, p-values will be adjusted using the chosen method (default is Benjamini-Hochberg \cite{Benjamini1995}, \Robject{padjMethod="BH"}, but others from \Rfunction{p.adjust} can be used). 

%You can also choose a different method for adjusting pvalue, such as:\\
%\begin{example}[H]                 
%\centering
%<<padjMethod,message=TRUE>>=
%re <- SimResults(pval=pval, labels=labels, padjMethod="holm" )
%re
%@
%\caption[set up method for adjusting pvalue when \Robject{padj} is missing]{set up method for adjusting pvalue when \Robject{padj} is missing} 
%\label{padjMethod}
%\end{example}

Note that \Robject{pval} (and \Robject{padj}) can be a vector or matrix (for a single method or multiple methods, respectively). 
If a matrix is used, each column should represent a score (p-value) for a classification method and 
each row should represent a feature. 

%---------------------------------------------------------
\section{Present a benchmark}
\subsection[\Rfunction{benchmarkR}]{\Rfunction{benchmarkR}: wrapper function to create a multi-panel performance assessment plot}
Following with the last example of Section \ref{sec:data}, a visualized benchmark result can be generated with: \\
\begin{example}[H]                 
\centering
 <<benchmarkR, message=TRUE, fig.show=TRUE, fig.width=10, fig.height=6, dev="pdf">>=
data(Pickrell)
re <- SimResults(pval=Pickrell$pval, labels=Pickrell$labels)
benchmarkR(re)
@
\caption[Usage of \Rfunction{benchmarkR}]{Usage of \Rfunction{benchmarkR} }
\label{benchmarkR}
\end{example}

\Rfunction{benchmarkR} will  produce a set of performance assessment plots for benchmarking.  A 3-panel plot is created with: an ROC curve (\Rfunction{rocX}), a false discovery (FD) plot (\Rfunction{fdX}) and a true-positive-rate versus achieved false-discovery plot (\Rfunction{powerFDR}).  All plots are augmented with calibration information of some form.  The \Rfunction{rocX} and \Rfunction{fdX} highlight a point on the curve for the chosen threshold (default: the method's FDR=5\%) while \Rfunction{powerFDR} shows the power versus the achieved FDR of a method.

\Rfunction{benchmarkR} provides many graphical parameters allowing flexible adjustment of each sub-panel. The graphical parameters of \Rfunction{par()} can directly work in \Rfunction{benchmarkR}, but follows one common rule:\\
\vspace{1em}
\begin{center}
    \begin{tabular}{ | l | }
      \hline
      \textbf{common rule of graphical parameters in \Rfunction{benchmarkR}:} \\
      \\
       \tabitem a single vector (e.g., `lwd=1') representing all sub-panels  \\
       \tabitem a list representing each sub-panel separately (e.g., `lwd=list(3,1,3)')\\
      \hline 
\end{tabular}
\end{center}
\vspace{1em}

An example is shown below: \\ 
 
\begin{example}[H]                 
\centering
 <<parameter, message=TRUE, fig.show=TRUE, fig.width=10, fig.height=6, dev="pdf">>=
benchmarkR(re, lwd=list(3,1,3), cex=2)
@
\caption[Graphical parameters in \Rfunction{benchmarkR}]{Graphical parameters in \Rfunction{benchmarkR} }
\label{parameter}
\end{example}

In this case `cex' are the same for all panels, while `lwd' are $3$ or $1$.  In addition, `legend' is 
plugged in \Rfunction{benchmarkR} function as a graphical parameter that can be also freely customized.    
\begin{example}[H]                 
\centering
 <<legend, message=TRUE, fig.show=TRUE, fig.width=10, fig.height=6, dev="pdf">>=
benchmarkR(re, legend=list(NULL,"topleft","topright"))
@
\caption[Set up `legend' in \Rfunction{benchmarkR}]{Set up `legend' in \Rfunction{benchmarkR} }
\label{legend}
\end{example}

\subsection[\Rfunction{powerFDR}]{\Rfunction{powerFDR}: power (TPR) versus achieved false discovery rate (FDR) plot}
\label{sec:powerFDR}

\Rfunction{powerFDR} calculates and plots power (true positive rate) versus the {\em achieved} FDR using adjusted P-values and the known true positives (labels).  By default, it calculates TPR and achieved FDR at three cutoffs: 0.01, 0.05 and 0.10. \\

The constructor function \Rfunction{powerFDR} will invisibly return an S4 object of \Rclass{powerFDR}. A typical usage for an object of \Rclass{SimResults} is:\\

\begin{example}[H]                 
\centering 
<<powerFDR, results="hide",message=TRUE, fig.show=TRUE, fig.width=6, fig.height=6, dev="pdf">>=
data(Pickrell)
re <- SimResults(pval=Pickrell$pval, labels=Pickrell$labels)
powerFDR(re, threshold=c(0.01,0.02,0.03,0.04,0.05), xlim=c(0,0.2))
@
\caption[\Rfunction{powerFDR} examples]{\Rfunction{powerFDR} examples}
\label{powerFDR}
\end{example}

Most of the graphical parameters such as `col', `cex', `pch', etc. from \Rfunction{par}, can be directly passed to \Rfunction{plot} for the power-FDR plots. `point.type', letter indicating how power-FDR values should be plotted: \Robject{"b"} for both points and lines; \Robject{"p"} for points only; and \Robject{"l"} for lines only. `col.line' and `lwd.line', `col' and `lwd' of line connecting power-FDR points, if `point.type' is either \Robject{"b"} or \Robject{"l"}. `lwd.threshold', `lty.threshold' and `col.threshold' are `wd', `lty' and `col' referred to the lines drawn for the threshold.

\begin{example}[H]                 
\centering
<<parameter-powerFDR, results="hide",message=TRUE, fig.show=TRUE, fig.width=6, fig.height=6, dev="pdf">>=
p <- powerFDR(re, plot=FALSE) 
plot(p, cex=2, pch=c(23,25), col=1:3, main="powerFDR plot", 
     lwd.line=2, cex.axis=1.5, col.threshold=4, lwd.threshold=2)
@          
\caption[Graphical parameters of \Rfunction{powerFDR} plot]{Graphical parameters of \Rfunction{powerFDR} plot}
\label{parameter-powerFDR}
\end{example}

A method's FDR is considered to be controlled if its achieved FDR falls below the set threshold; 
if this happens, plotted power-FDR points are filled-in. power-FDR points are unfilled, 
or empty, if the FDR is not controlled and is equal to or greater than the cutoff it is assessed at. 
Note that the fill-unfill option is only compatible with `pch' values of 21 to 25. Visually, this 
means that for a given threshold, a point (of the same color) will be filled if it falls left of 
the threshold line, and will be unfilled if it sits on or to the right of the threshold line.\\

The function \Rfunction{powerFDR} can also directly work with input value \Robject{padj}, 
\Robject{padj} and \Robject{labels}. \\

\begin{example}[H]                 
\centering
<<direct-powerFDR, results="hide",message=TRUE, fig.show=TRUE, fig.width=6, fig.height=6, dev="pdf">>= 
data(calibration)
padj <- calibration$padj
labels <- calibration$labels
powerFDR(padj=padj, labels=labels, xlim=c(0,.3))
@          
\caption[Direct usage of \Robject{powerFDR} plot without \Robject{SimResults}]{Direct usage of \Robject{powerFDR} plot without \Robject{SimResults}}
\label{direct-powerFDR}
\end{example}




\subsection[\Rfunction{rocX}]{\Rfunction{rocX}: ROC curve augmented with X point}
\label{sec:rocX}
 \Rfunction{rocX} will produce a ROC plot with an X point marking the location of the method's FDR (at a chosen level), using the features of \Rpackage{ROCR} \cite{Sing2005}.  The special feature of \Robject{rocX} beyond \Rpackage{ROCR} is that an X point is employed to shows the actual position along the ROC curve (e.g., at the method's 5\% FDR point).\\

The function \Rfunction{rocX} is just the constructor to build a \Rclass{rocX} object. It can be simply used as:  
\begin{example}[H]                 
\centering
 <<rocX, message=TRUE, fig.show=TRUE, fig.width=6, fig.height=6, dev="pdf">>=
data(Pickrell)
re <- SimResults(pval=Pickrell$pval, labels=Pickrell$labels)
r <- rocX(re)
@
\caption[\Robject{rocX}]{\Robject{rocX}}
\label{rocX}
\end{example}

\Rfunction{rocX} will call \Rclass{prediction} and \Rclass{performance} from the \Rpackage{ROCR} package using the p-value
and labels from the \Robject{SimResults} object.  Additionally, the value of TPR and FPR corresponding to the threshold 
X will be calculated from the adjust P-values.  We introduced \Rfunction{rocX} to augment the standard ROC curves in order to show where on the curve a method is operating. \\

For convenience, an \Robject{rocX} object can be re-plotted by function \Rfunction{plot} allowing flexible resetting of graphical parameters from \Rfunction{par()}. \\

There are several special graphical parameters (`cexX', `pchX' and `colX') referring to setting of X point of \Rclass{rocX}. You can simply change them as:\\

\begin{example}[H]                 
\centering
 <<replot-rocX, message=TRUE, fig.show=TRUE, fig.width=9, fig.height=4.5, dev="pdf">>=
par(mfrow=c(1,2))
plot(r, lwd=4, cex=4, col=1:3)
plot(r, cexX=3, lwdX=3)
@
\caption[re-plot of \Robject{rocX}, using special graphical parameters]{re-plot of \Robject{rocX}, using special graphical parameters}
\label{replot-rocX}
\end{example}  

In the next examples, additional variations are shown.  For example, you can remove X, if it is not needed. Or you can change `xlim'. \\

\begin{example}[H]                 
\centering
 <<X, results="hide", fig.show=TRUE, fig.width=9, fig.height=4.5, dev="pdf">>=
par(mfrow=c(1,2))
rocX(re, thresholdX=NULL)
rocX(re, xlim=c(0,.5))
@
\caption[Various examples of \Rfunction{rocX}]{Various examples of \Rfunction{rocX}}
\label{X}
\end{example}   

In addition, \Rfunction{rocX} allows any flexible transformation formula for input data, in order to have more resolution along the ROC curve.     
\vspace{1em}
\begin{center}
    \begin{tabular}{ | l | }
      \hline
      \textbf{transformation:} \\
      \\
      =``1-x'' (default setting)\\
      =``-log10(x)'' (pval or padj is sparse.) \\
      =``x'' (inverse score) \\
      =``f(x)'' (any other functions) \\   
      \hline 
\end{tabular}
\end{center}
\vspace{1em}


%For instance, you can define your own ``transformation'' function like this way.

%\begin{example}[H]                 
%\centering
% <<transformation, results="hide", fig.show=TRUE, fig.width=6, fig.height=6, dev="pdf">>=
%rocX(re,  transformation="-log10(x^5)")
%@
%\caption[transformation of \Robject{pval} and \Robject{padj}]{transformation of \Robject{pval} and \Robject{padj}}
%\label{transformation}
%\end{example} 

\Robject{rocX} can be separated into several sub-ROC curves by using the `stratify' factor, which can be useful to subdivide
results according to other features of the assay (e.g., gene expression strength):
 
 \begin{example}[H]                 
\centering
<<stratify, results="hide", fig.show=TRUE, fig.width=9, fig.height=4.5, dev="pdf">>=
rm <- rowMeans(Pickrell$counts)
f <- cut(log(rm), 2)
re <- SimResults(pval=Pickrell$pval, labels=Pickrell$labels, stratify=f)
par(mfrow=c(1,2), mar=c(2,5,3,1), mgp=c(2.6,1,0))
rocX(re, ylim=c(0,1))
@
\caption[`stratify' factor  of \Robject{rocX}]{`stratify' factor  of \Robject{rocX}}
\label{transformation}
\end{example} 

% res1 <- re[f==0,] 
% res2 <- re[f==1,]
% res3 <- re[f==2,] 
% res4 <- re[f==3,] 
% r1 <- rocX(res1, plot=FALSE)
% r2 <- rocX(res2, plot=FALSE)
% r3 <- rocX(res3, plot=FALSE)
% r4 <- rocX(res4, plot=FALSE) 
% rl <- rocXList(r1=r1, r2=r2, r3=r3, r4=r4)


\subsection[\Rfunction{fdX}]{\Rfunction{fdX}: false discovery plot augmented with X point}
\label{sec:fdX}


\Rfunction{fdX} plots the cumulative number of false discoveries versus the number of top ranked features with an X point marking the location of the method's FDR (at a chosen level).The constructor function \Rfunction{fdX} will produce an S4 object of \Robject{fdX}. \\

A couple quick examples of \Rfunction{fdX} include:

\begin{example}[H]                 
\centering
<<fdX, message=TRUE, fig.show=TRUE, fig.width=6, fig.height=6, dev="pdf">>=
data(Pickrell)
re <- SimResults(pval=Pickrell$pval, labels=Pickrell$labels)
f <- fdX(re)
@
\caption[\Rfunction{fdX} examples]{\Rfunction{fdX} examples}
\label{fdX}
\end{example} 

The \Rfunction{fdX} function (and objects) use almost all the characteristics of the \Rfunction{rocX} function, including `thresholdX', `transformation', special graphical parameters (`cexX', `pchX' and `colX')  and so on. A customized example is:\\

\begin{example}[H]                 
\centering
<<fdX_c, message=TRUE, fig.show=TRUE, fig.width=6, fig.height=6, dev="pdf">>=
plot(f, lwd=2, col=1:3, pchX=9:11, cex=3, legend=list("topleft"))
@
\caption[ A customized \Rfunction{fdX} example]{A customized \Rfunction{fdX} example}
\label{fdX_c}
\end{example} 


%---------------------------------------------------------
\section{Session info}
%---------------------------------------------------------
<<sessInfo, results="asis", echo=FALSE>>=
toLatex(sessionInfo())
@

\bibliography{myrefs}

\end{document}
